version: '3.8'

services:
  hw_db:
    image: postgres:12-alpine
    container_name: backend_structure_db
    environment:
      POSTGRES_DB: backend_structure_db
      POSTGRES_USER: a_user
      POSTGRES_PASSWORD: a_password
    volumes:
      - './.docker_pgdata:/var/lib/postgresql/data'
    ports:
      - '5466:5432'
