export { getStatsCtrl } from './stats/get-stats.ctrl';
export { createBetsCtrl } from './bets/create-bets.ctrl';
export { updateEventCtrl } from './events/update-event.ctrl';
export { createEventsCtrl } from './events/create-events.ctrl';
export { transactionsCtrl } from './transaction/transaction.ctrl';
export { createUserCtrl } from './user/create-user.ctrl';
export { updateUserCtrl } from './user/update-user.ctrl';
export { getUserByIdCtrl } from './user/get-user.ctrl';
export  { healthCtrl } from './health/health.ctrl';